/**
 * Design tokens pipeline — src/tokens/tokens.json (DTCG) is the single source.
 *  → src/styles/tokens.css  (web: light + dark mode custom properties)
 *  → export/tokens.json     (Figma Variables / Tokens Studio import)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

type Token = { $value: unknown; $type?: string; $description?: string; $extensions?: { mode?: Record<string, unknown> } };
type Group = { [key: string]: Group | Token | string | undefined };

const root = resolve(import.meta.dirname, '..');
const source = JSON.parse(readFileSync(resolve(root, 'src/tokens/tokens.json'), 'utf8')) as Group;

const isToken = (node: unknown): node is Token => typeof node === 'object' && node !== null && '$value' in node;

function walk(group: Group, path: string[] = [], out: { name: string; token: Token }[] = []) {
  for (const [key, node] of Object.entries(group)) {
    if (key.startsWith('$')) continue;
    if (isToken(node)) out.push({ name: [...path, key].join('-'), token: node });
    else if (typeof node === 'object' && node) walk(node as Group, [...path, key], out);
  }
  return out;
}

const cssValue = (value: unknown) =>
  Array.isArray(value) ? value.map((v) => (/\s/.test(String(v)) ? `"${v}"` : v)).join(', ') : String(value);

const tokens = walk(source);
// px dimensions also get a unitless `-n` twin so Sections can scale them: calc(var(--size-h1-n) * var(--px))
const light = tokens.flatMap(({ name, token }) => {
  const value = cssValue(token.$value);
  const px = /^(-?[\d.]+)px$/.exec(value);
  return [`  --${name}: ${value};`, ...(px ? [`  --${name}-n: ${px[1]};`] : [])];
});
const dark = tokens
  .filter(({ token }) => token.$extensions?.mode?.dark !== undefined)
  .map(({ name, token }) => `  --${name}: ${cssValue(token.$extensions!.mode!.dark)};`);

const css = `/* AUTO-GENERATED by scripts/build-tokens.ts from src/tokens/tokens.json — do not edit. */
:root {
  color-scheme: light;
${light.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${dark.map((l) => '  ' + l).join('\n')}
  }
}

:root[data-theme='dark'] {
  color-scheme: dark;
${dark.join('\n')}
}
`;

function write(file: string, content: string) {
  const path = resolve(root, file);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`tokens → ${file}`);
}

write('src/styles/tokens.css', css);
write('export/tokens.json', JSON.stringify(source, null, 2) + '\n');
